### PR TITLE
study the optimal configuration of amplifiers #777

### PR DESCRIPTION
**Pull request by Deeplus**

### CODE REVIEW

**Comment by danglotb** [comment]
Hello @Deeplus 

Thank you for investigating this.

What is the structure of your folders? Why there are `A1`, `A10` and `A11`? What does it mean?

Could you update the folder with the month using a lowercase `j` for the first letter to be consistent with other folders?

Thank you.

**Comment by Deeplus** [comment]
Hi @danglotb 

Thanks for your reply.

Q1&Q2: 
**A represents the I-Amplification.**
A1=MethodAdd, A2=MethodRemove, A3=TestDataMutator, ... A11=NullifierAmplifier.

**P represents the Project.**
P1=javapoet; P2=mybatis-3; P3=traccar; P4=stream-lib; P5=mustache.java;
P6=twilio-java; P7=jsoup; P8=protostuff; P9=logback; P10=retrofit.

 I plan to modify the structure of folders.

- Root directory: june-2019
-  One level down: june-2019/1, 2, 3, ... 11 ( the number denotes the type of combination scenarios, eg. 1 means a combination of single I-Amplification method; 2 means a combination of double I-Amplification methods, ... 11 means a combination of eleven I-Amplification methods,)

- One level down: june-2019/1/A1,A2, A3, ... A11;  june-2019/2/A1A2, A1A3, ... A10A11; ... june-2019/11/A1A2A3A4A5A6A7A8A9A10A11 

- Last level down: june-2019/1/A1/P1,P2,P3, ... P10; june-2019/1/A2/P1,P2,P3, ... P10.

**Comment by danglotb** [comment]
That looks good, thank you!

Have you an idea to keep the signification of the `P`s and the `A`s?

**Comment by Deeplus** [comment]
Actually, I wanna reduce the numbers of combination scenarios.

- First step: apply 11 kinds of amplifier methods to test 10 Java projects separately. Calculate the mean of each method.

- Second step: classify amplifier methods into  Method calls (MethodAdd, MethodRemove, MethodGenerator), Literals(TestData, All, Null, String, Number, Boolean) and Test Object (ReturnValue).

- Last step: Find the optimal one.

**Comment by monperrus** [comment]
This is outdated results, @Deeplus will create a new one.

**Pull request closed without merging**
